# Generated by Django 2.2.1 on 2019-05-21 03:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='start_date',
            field=models.DateField(default=datetime.date(2019, 5, 21)),
        ),
    ]
