# Generated by Django 2.2.1 on 2019-05-21 03:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0003_auto_20190521_0522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compaign',
            name='end_date',
            field=models.DateField(default=datetime.timedelta(7)),
        ),
    ]
