# Generated by Django 2.2.1 on 2019-05-21 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0005_auto_20190521_0526'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Compaign',
            new_name='Campaign',
        ),
    ]
