# Generated by Django 2.2.1 on 2019-05-22 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0007_campaign_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='Budget',
            new_name='budget',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='campaign',
            name='start_date',
        ),
        migrations.AddField(
            model_name='campaign',
            name='created_at',
            field=models.DateField(auto_now=True),
        ),
    ]
